# $FreeBSD$
#

    COMMENT = Wayland libraries, compositors and clients

    SUBDIR += libepoll-shim
    SUBDIR += libgudev
    SUBDIR += libinput
    SUBDIR += libkbdev
    SUBDIR += libudev-devd
    SUBDIR += libwacom
    SUBDIR += wayland
    SUBDIR += wayland-protocols
    SUBDIR += weston

#    SUBDIR += libevdev (should we patch to use dev/evdev/input.h for evdev kernels?
#    SUBDIR += wlc
#    SUBDIR += efl-wl
#    SUBDIR += sway

.include <bsd.port.subdir.mk>
