# $FreeBSD$

PORTNAME=	xf86-video-nouveau
PORTVERSION=	1.0.12
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org nouveau display driver

XORG_CAT=	driver

LIB_DEPENDS=	libdrm_nouveau.so:graphics/libdrm

.include <bsd.port.mk>
