# $FreeBSD$

PORTNAME=	xf86-input-libinput
PORTVERSION=	0.19.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org libinput driver

XORG_CAT=	driver
USES=		pkgconfig pathfix

LIB_DEPENDS= libinput.so:${PORTSDIR}/wayland/libinput

.include <bsd.port.mk>
