# $FreeBSD$

PORTNAME=	libkbdev
PORTVERSION=	0.1
CATEGORIES=	wayland

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Keyboard event library


USE_GITHUB=	yes
GH_ACCOUNT=	ivadasz
GH_TAGNAME=	43b8ebf


.include <bsd.port.mk>
