# $FreeBSD$

PORTNAME=	wayland-protocols
PORTVERSION=	0.0
CATEGORIES=	graphics

MAINTAINER=	kwm@FreeBSD.org
COMMENT=	Wayland protocols

# until offical release is out
USE_GITHUB=	yes
GH_ACCOUNT=	wayland-project
GH_TAGNAME=	a5585f3

USES=		autoreconf
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
